import "./globals.css";
import styles from "../app/page.module.css";
import Link from "next/link";
import Aside from "@/Comps/Aside";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={styles.body}>
        <header className={styles.header}>
          <h1>
            <Link href="/">나만의 블로그</Link>
          </h1>
        </header>
        <section className={styles.section}>
          <aside>
            <Aside />
          </aside>
          <div className={styles.context}>{children}</div>
        </section>
      </body>
    </html>
  );
}
